name: Auto Bump Version
on:
  push:
    branches:
      - PSG-1550-testing
  # pull_request:
  #   branches:
  #     - main

env:
  BRANCH: ${GITHUB_REF_NAME}

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get Previous Tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0
      - name: Echo Previous Tag
        run: |
          echo "${{ steps.previoustag.outputs.tag }}"
      - name: Get Next Version
        id: nexttag
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - name: Echo Next Versions
        run: |
          echo "${{ steps.nexttag.outputs.major}}"
          echo "${{ steps.nexttag.outputs.minor}}"
          echo "${{ steps.nexttag.outputs.patch}}"
          echo "${{ steps.nexttag.outputs.v_major}}"
          echo "${{ steps.nexttag.outputs.v_minor}}"
          echo "${{ steps.nexttag.outputs.v_patch}}"
          echo "Branch: ${{ env.BRANCH }}"
          echo "{\"version\": \"${{ steps.previoustag.outputs.tag }}-${GITHUB_SHA}\"}"
      - name: Update version
        id: update-settings-version
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "settings.json"
          dir: "./Sources/Passage/Resources/"
          json: '{"version": "${{ steps.previoustag.outputs.tag }}-${GITHUB_SHA}"}'
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Updated version"
          branch: "${{ env.BRANCH }}"
