name: Auto Bump Version
on:
  push:
    branches:
      - PSG-1550-testing
  # pull_request:
  #   branches:
  #     - main

env:
  BUMP_SUFFIX: ${GITHUB_SHA}

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Bump Version
        uses: michmich112/version-bumper@master
        with:
          options-file: "./auto-version-options.json"
          github-token: ${{ secrets.GITHUB_TOKEN }}
