name: Auto Bump Version
on:
  push:
    branches:
      - PSG-1550-testing
  # pull_request:
  #   branches:
  #     - main

env:
  BUMP_SUFFIX: ${GITHUB_SHA}

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - name: Bump Version
        uses: michmich112/version-bumper@master
        with:
          scheme: org_semantic
          version-file: "./Sources/Passage/Resources/settings.json"
          files: >
            ["./Sources/Passage/Resources/settings.json"]
          rules: >
            [
                  {
                    "trigger": "commit",
                    "branch": "PSG-1550-testing",
                    "suffix": "-${GITHUB_SHA}"
                  }
            ]
          github-token: ${{ secrets.GITHUB_TOKEN }}
