name: Generate Documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-documentation:
    name: Generate Documentation
    runs-on: macos-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Documentation
        run: xcodebuild docbuild -scheme Passage -destination generic/platform=iOS  OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs --hosting-base-path passage-ios"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated and Updated Documentation

  build-documentation-archive:
    name: Build Documentation Archive
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create doc archive
        run: |
          export HOMED = PWD
          echo $HOMED
