name: Generate Documentation
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-documentation:
    name: Generate Documentation
    runs-on: macos-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Documentation
        run: xcodebuild docbuild -scheme Passage -destination generic/platform=iOS  OTHER_DOCC_FLAGS="--transform-for-static-hosting --output-path docs --hosting-base-path passage-ios"

      - name: Generate doccarchive
        run: xcodebuild docbuild -scheme Passage -derivedDataPath ./tmpdocs -destination generic/platform=iOS

      - name: Create doc archive
        run: |
          pushd tmpdocs/Build/Products/Debug-iphoneos
          zip -r $OLDPWD/docs/Passage.doccarchive.zip Passage.doccarchive
          popd
          rm -rf tmpdocs

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generated and Updated Documentation
