name: integration tests passage-ios
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

jobs:
  integration-test-iOS-16:
    name: Build and Integration Tests iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Schemes
        run: xcodebuild -list

      - name: Test iOS
        run: xcodebuild clean build-for-testing test -scheme IntegrationTest -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro"
