name: PR Handler for passage-ios
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

jobs:
  unit-test-iOS-16:
    name: Build and Unit Test iOS 16
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test iOS 16.2
        run: xcodebuild test -scheme Passage -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14 Pro"

  integration-test-iOS-16:
    name: Build and Integration Tests iOS 16
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Schemes
        run: xcodebuild -list

      - name: Test iOS 16.2
        run: xcodebuild test -scheme IntegrationTest -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14 Pro" PASSAGE_AUTH_TOKEN="${{ env.PASSAGE_AUTH_TOKEN }}" MAILOSAUR_API_KEY="${{ secrets.MAILOSAUR_API_KEY }}"

  bump:
    runs-on: ubuntu-latest
    needs: [unit-test-iOS-16, integration-test-iOS-16]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Previous Tag
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.0.0

      - name: Configure Branch and new Version
        id: newversion
        run: |
          echo "version=${{ steps.previoustag.outputs.tag }}-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Update version
        id: update-settings-version
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "settings.json"
          dir: "./Sources/Passage/Resources/"
          json: "{\n    \"version\": \"${{ steps.newversion.outputs.version }}\"\n}"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generated and Updated Version to ${{ steps.newversion.outputs.version }}"
