name: Test Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

jobs:
  unit-test-iOS:
    name: Build and Unit Test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/

      - name: Test iOS
        run: xcodebuild clean build-for-testing test -scheme Passage -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro"

  integration-test-iOS:
    name: Build and Integration Tests iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode 15.0.1
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app/Contents/Developer/usr/bin/

      - name: List Schemes
        run: xcodebuild -list

      - name: Test iOS
        run: xcodebuild clean build-for-testing test -scheme IntegrationTest -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro" PASSAGE_AUTH_TOKEN="${{ env.PASSAGE_AUTH_TOKEN }}" MAILOSAUR_API_KEY="${{ secrets.MAILOSAUR_API_KEY }}"
