name: Test Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

jobs:
  unit-test-iOS-17:
    name: Build and Unit Test iOS 17
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Available Simulators
        run: xcrun simctl list devices

      - name: Test iOS 17.4
        run: xcodebuild clean build-for-testing test -scheme Passage -sdk iphonesimulator17.4 -destination "OS=17.4,name=iPhone 15 Pro"

  integration-test-iOS-17:
    name: Build and Integration Tests iOS 17
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: List Schemes
        run: xcodebuild -list

      - name: Test iOS 17.4
        run: xcodebuild clean build-for-testing test -scheme IntegrationTest -sdk iphonesimulator17.4 -destination "OS=17.4,name=iPhone 15 Pro" PASSAGE_AUTH_TOKEN="${{ env.PASSAGE_AUTH_TOKEN }}" MAILOSAUR_API_KEY="${{ secrets.MAILOSAUR_API_KEY }}"
