name: Test Pull Request
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  PASSAGE_AUTH_TOKEN: ${{ secrets.PASSAGE_AUTH_TOKEN }}
  MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }}

jobs:
  integration-test-iOS:
    name: Build and Integration Tests iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Xcode 15.4
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.4'

      - name: List Schemes
        run: xcodebuild -list

      - name: Test iOS
        run: xcodebuild clean build-for-testing test -scheme IntegrationTest -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro" PASSAGE_AUTH_TOKEN="${{ env.PASSAGE_AUTH_TOKEN }}" MAILOSAUR_API_KEY="${{ secrets.MAILOSAUR_API_KEY }}"
