name: Trigger iOS App UI Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-ui-test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger UI Test Workflow in iOS App Repo
        uses: convictional/trigger-workflow-and-wait@v1.6.3
        with:
          owner: passageidentity
          repo: passage-ios-uitest-app
          github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          workflow_file_name: ui-tests.yml
          inputs: '{"passage_ios_branch_name": "${{ github.head_ref }}"}'
