name: unit test passage-ios
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-test-iOS-17:
    name: Build and Unit Test iOS 17
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test iOS 17.0
        run: xcodebuild test -scheme Passage -sdk iphonesimulator17.0 -destination "OS=17.0,name=iPhone 15 Pro"
