name: unit test passage-ios
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-test-iOS-16:
    name: Build and Unit Test iOS 16
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test iOS 16.2
        run: xcodebuild test -scheme Passage -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14 Pro"
