name: unit test passage-ios
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unit-test-iOS:
    name: Build and Unit Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test iOS
        run: xcodebuild clean build-for-testing test -scheme Passage -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 15 Pro"
