name: Verify Cocoapod
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  verify-pod:
    name: Verify Pod
    runs-on: macos-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Lint Cocoapod
        if: ${{ github.event.inputs.release-type == 'major' }}
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
