name: Passage iOS Unit Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: >-
          xcodebuild test -scheme Passage -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14 Pro"
