name: unit test passage-ios
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  unit-test-iOS-16:
    name: Build and Unit Test iOS 16
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test iOS 16.2
        run: xcodebuild test -scheme Passage -sdk iphonesimulator16.2 -destination "OS=16.2,name=iPhone 14 Pro"

  unit-test-iOS-15:
    name: Build and Unit Test iOS 15
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Force Xcode 13
        run: sudo xcode-select -switch /Applications/Xcode_13.4.app

      - name: Test iOS 15.5
        run: xcodebuild test -scheme Passage -sdk iphonesimulator15.5 -destination "OS=15.5,name=iPhone 13 Pro"
